version: '3'

services:
    api-gobarber:
        build: .
        restart: always
        container_name: api-gobarber
        volumes:
            - .:/home/node/api
            - /home/node/api/node_modules
        ports:
            - '3333:3333'
        networks:
            - nodejs-api

networks:
    nodejs-api:
        driver: bridge